Repository Anidion/flatmates, pull requests merged in 2024-11, with the labels that each got.

#25 1. Added the variant prop the Button component; 2. Updated all button…
  FlatMate/Components/ButtonView.swift
  FlatMate/View/LoginView.swift
  FlatMate/View/OnboardingPageView.swift
  FlatMate/View/SignupView.swift
Labels: New Feature

#32 added the link variant for button component and update all button com…
  FlatMate/Components/ButtonView.swift
  FlatMate/View/LoginView.swift
  FlatMate/View/OnboardingPageView.swift
  FlatMate/View/SignupView.swift
Labels: New Feature

#38 Feature/#35 authentication backend integration
  FlatMate.xcodeproj/project.pbxproj
  FlatMate.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FlatMate/Components/InputView.swift
  FlatMate/ContentView.swift
  FlatMate/FlatMateApp.swift
  FlatMate/GoogleService-Info.plist
  FlatMate/Models/User.swift
  FlatMate/View/LandingPageView.swift
  FlatMate/View/LoginView.swift
  FlatMate/View/ProfileView.swift
  FlatMate/View/ResetPasswordView.swift
  FlatMate/View/SignupView.swift
  FlatMate/ViewModel/AuthViewModel.swift
  GoogleService-Info.plist
Labels: New Feature

#41 updated the edit profile page
  FlatMate/View/EditProfileView.swift
Labels: New Feature

#44 Finished backend integration of the onboarding pages
  FlatMate/Components/RoundedInputField.swift
  FlatMate/ContentView.swift
  FlatMate/Models/User.swift
  FlatMate/View/OnboardingPageView.swift
  FlatMate/ViewModel/AuthViewModel.swift
Labels: New Feature

#45 refactor edit profile page based on the Figma design file
  FlatMate/View/EditProfileView.swift
Labels: Technical Debt

#50 Migrated Changes for Landing and Matches Screens
  FlatMate/Assets.xcassets/Logo Straight Blue.imageset/Contents.json
  FlatMate/Assets.xcassets/Logo Straight Blue.imageset/Logo Straight Blue.png
  FlatMate/Assets.xcassets/landing1.imageset/Contents.json
  FlatMate/Assets.xcassets/landing1.imageset/landing1.jpg
  FlatMate/Assets.xcassets/landing2.imageset/Contents.json
  FlatMate/Assets.xcassets/landing2.imageset/landing2.jpg
  FlatMate/Assets.xcassets/landing3.imageset/Contents.json
  FlatMate/Assets.xcassets/landing3.imageset/landing3.jpg
  FlatMate/Assets.xcassets/landing4.imageset/Contents.json
  FlatMate/Assets.xcassets/landing4.imageset/landing4.jpg
  FlatMate/Assets.xcassets/person1.imageset/Contents.json
  FlatMate/Assets.xcassets/person1.imageset/person1.png
  FlatMate/Assets.xcassets/person2.imageset/Contents.json
  FlatMate/Assets.xcassets/person2.imageset/person2.png
  FlatMate/Assets.xcassets/person3.imageset/Contents.json
  FlatMate/Assets.xcassets/person3.imageset/person3.png
  FlatMate/Assets.xcassets/person4.imageset/Contents.json
  FlatMate/Assets.xcassets/person4.imageset/person4.png
  FlatMate/Assets.xcassets/person5.imageset/Contents.json
  FlatMate/Assets.xcassets/person5.imageset/person5.png
  FlatMate/Components/LandingPageStep.swift
  FlatMate/Components/MatchRow.swift
  FlatMate/Models/MatchModel.swift
  FlatMate/View/LandingPageView.swift
  FlatMate/View/MessagesView.swift
Labels: bug, New Feature, Technical Debt

#60 Tech debt/#59 onboarding page refactor
  FlatMate/Components/OnboardingPage.swift
  FlatMate/Components/ProgrammaticInput.swift
  FlatMate/Constants/Constants.swift
  FlatMate/ContentView.swift
  FlatMate/View/EditProfileView.swift
  FlatMate/View/LocationSearchView.swift
  FlatMate/View/OnboardingPageView.swift
  FlatMate/ViewModel/AuthViewModel.swift
Labels: Technical Debt

#67 43_ Bug fix: Disable auto-capitalization for input field in InputView component.
  FlatMate/Components/InputView.swift
Labels: New Feature

#69 Feature/#46 integrate edit profile backend
  FlatMate.xcodeproj/project.pbxproj
  FlatMate/Components/GenderPicker.swift
  FlatMate/Components/ProfileButton.swift
  FlatMate/Components/ProfileField.swift
  FlatMate/ContentView.swift
  FlatMate/Models/User.swift
  FlatMate/View/EditProfileView.swift
  FlatMate/View/MainView.swift
  FlatMate/View/OnboardingPageView.swift
  FlatMate/View/ProfileView.swift
  FlatMate/ViewModel/AuthViewModel.swift
Labels: New Feature

#73 finally have the edit profile page working
  FlatMate/ContentView.swift
  FlatMate/View/EditProfileView.swift
  FlatMate/View/ProfileView.swift
  FlatMate/ViewModel/AuthViewModel.swift
Labels: New Feature

#75 Added Terms and Privacy Disclaimer
  FlatMate/View/LoginView.swift
  FlatMate/View/SignupView.swift
Labels: New Feature

#78 Update Logo for Login, Signup, and Profile View
  FlatMate/View/LoginView.swift
  FlatMate/View/ProfileView.swift
  FlatMate/View/SignupView.swift
Labels: Technical Debt

#77 Feature/#76 swiping pages dynamically
  FlatMate/Components/ProfileCardView.swift
  FlatMate/View/SwipePageView.swift
Labels: New Feature

#80 Feature/#79 integration swiping matching functionality
  FlatMate/Models/SwipeCardsView.swift
  FlatMate/Services/MatchService.swift
  FlatMate/View/SwipePageView.swift
  FlatMate/View/YouMatchedView.swift
  FlatMate/ViewModel/SwipeViewModel.swift
Labels: New Feature

#87 fixed the bug where users' own profiles are displayed on the swiping …
  FlatMate/View/MatchNotificationView.swift
  FlatMate/View/SwipePageView.swift
  FlatMate/ViewModel/SwipeViewModel.swift
Labels: bug

#86 Bug fix, clean code, and match button goes to chat
  FlatMate/Models/ChatUtilities.swift
  FlatMate/View/MessagesView.swift
  FlatMate/View/YouMatchedView.swift
  FlatMate/ViewModel/MessagesViewModel.swift
Labels: New Feature, bugfix

#91 fixed the bug where the same profile is displayed every time the home…
  FlatMate/ViewModel/SwipeViewModel.swift
Labels: bugfix
